# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
_translate = QtCore.QCoreApplication.translate

import memoryModule

timeIntervals = memoryModule.timeIntervals

def secondsToWDHMS(seconds):
    weeks, modWeeks = seconds // 604800, seconds % 604800
    days, modDays = modWeeks // 86400, modWeeks % 86400
    hours, modHours = modDays // 3600, modDays % 3600
    minutes, seconds = modHours // 60, modHours % 60

    return weeks, days, hours, minutes, seconds

stages = []

currentUi = None

class stage():
    def __init__(self, stageNum, time):
        self.stageNum = stageNum
        self.time = time

        self.elements = {}
        currentUi.createTimingTopicBox( self)
        
        stages.append(self)

    def removeStage(self):
        self.elements["GroupBox"].deleteLater()

        for stageItem in stages:
            if stageItem.stageNum > self.stageNum:
                stageItem.stageNum -= 1
                stageItem.elements["GroupBox"].setTitle(_translate("TimingsDialog", f"Stage {stageItem.stageNum}"))

        stages.remove(self)

    def getTime(self):
        elements = self.elements
        weeks = elements["WeekBox"].value() * 604800
        days = elements["DayBox"].value() * 86400
        hours = elements["HourBox"].value() * 3600
        minutes = elements["MinuteBox"].value() * 60
        seconds = elements["SecondBox"].value()

        return weeks + days+  hours + minutes + seconds


class Ui_TimingsDialog(object):
    def setupUi(self, TimingsDialog):
        global currentUi
        currentUi = self

        self.TimingsDialog = TimingsDialog

        TimingsDialog.setObjectName("TimingsDialog")
        TimingsDialog.resize(503, 538)
        self.buttonBox = QtWidgets.QDialogButtonBox(TimingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 500, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.scrollArea = QtWidgets.QScrollArea(TimingsDialog)
        self.scrollArea.setGeometry(QtCore.QRect(19, 16, 461, 431))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 438, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)


        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.ResetTimings = QtWidgets.QPushButton(TimingsDialog, clicked = lambda: self.resetTimings())
        self.ResetTimings.setGeometry(QtCore.QRect(130, 500, 101, 28))
        self.ResetTimings.setObjectName("ResetTimingsButton")

        self.AddStage = QtWidgets.QPushButton(TimingsDialog, clicked = lambda: self.addStage())
        self.AddStage.setGeometry(QtCore.QRect(20, 500, 101, 28))
        self.AddStage.setObjectName("AddStageButton")

        
        self.buttonBox.accepted.connect(lambda : self.getTimeIntervals())
        self.buttonBox.rejected.connect(lambda : self.closeWindow()) 
        QtCore.QMetaObject.connectSlotsByName(TimingsDialog)

        TimingsDialog.setWindowTitle(_translate("TimingsDialog", "TimingsDialog"))
        self.ResetTimings.setText(_translate("TimingsDialog", "Reset Timings"))
        self.AddStage.setText(_translate("TimingsDialog", "Add Stage"))

                
        for stageNum in timeIntervals:
            stage(int(stageNum), timeIntervals[stageNum])

    def resetTimings(self):
        for stageItem in stages:
            stageItem.elements["GroupBox"].deleteLater()
        
        stages.clear()

        stage(1, 600)
        stage(2, 10800)
        stage(3, 86400)
        stage(4, 172800)
        stage(5, 604800)

    def addStage(self):
        stage(stages.__len__() + 1, 172800)

    def getTimeIntervals(self):
        intervals = {}

        for stageItem in stages:
            intervals[str(stageItem.stageNum)] = stageItem.getTime()

        memoryModule.setTimeIntervals(intervals)
        
        global timeIntervals
        timeIntervals = intervals
        
        self.TimingsDialog.close()

    def createTimingTopicBox(self, stage):
        weeks, days, hours, minutes, seconds = secondsToWDHMS(stage.time)
        
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 421, 81))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)

        SP = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        SP.setHorizontalStretch(0)
        SP.setVerticalStretch(0)
        self.groupBox.setSizePolicy(SP)

        self.groupBox.setMinimumSize(421, 81)
        stage.elements["GroupBox"] = self.groupBox


        self.WeekSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.WeekSpinBox.setGeometry(QtCore.QRect(30, 30, 42, 22))
        self.WeekSpinBox.setObjectName("WeekSpinBox")
        self.WeekSpinBox.setValue(weeks)
        stage.elements["WeekBox"] = self.WeekSpinBox

        self.DaySpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.DaySpinBox.setGeometry(QtCore.QRect(100, 30, 42, 22))
        self.DaySpinBox.setMaximum(6)
        self.DaySpinBox.setValue(days)
        self.DaySpinBox.setObjectName("DaySpinBox")   
        stage.elements["DayBox"] = self.DaySpinBox

        self.HourSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.HourSpinBox.setGeometry(QtCore.QRect(170, 30, 42, 22))
        self.HourSpinBox.setMaximum(23)
        self.HourSpinBox.setValue(hours)
        self.HourSpinBox.setObjectName("HourSpinBox")
        stage.elements["HourBox"] = self.HourSpinBox

        self.MinuteSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.MinuteSpinBox.setGeometry(QtCore.QRect(240, 30, 42, 22))
        self.MinuteSpinBox.setMaximum(59)
        self.MinuteSpinBox.setValue(minutes)
        self.MinuteSpinBox.setObjectName("MinuteSpinBox")
        stage.elements["MinuteBox"] = self.MinuteSpinBox

        self.SecondSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.SecondSpinBox.setGeometry(QtCore.QRect(310, 30, 42, 22))
        self.SecondSpinBox.setMaximum(59)
        self.SecondSpinBox.setValue(seconds)
        self.SecondSpinBox.setObjectName("SecondSpinBox")
        stage.elements["SecondBox"] = self.SecondSpinBox

        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 60, 55, 16))
        self.label.setObjectName("label")
        stage.elements["Label"] = self.label
        
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 55, 16))
        self.label_2.setObjectName("label_2")
        stage.elements["Label_2"] = self.label_2
                
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(170, 60, 55, 16))
        self.label_3.setObjectName("label_3")
        stage.elements["Label_3"] = self.label_3

        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 60, 55, 16))
        self.label_4.setObjectName("label_4")
        stage.elements["Label_4"] = self.label_4

        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(310, 60, 61, 16))
        self.label_5.setObjectName("label_5")
        stage.elements["Label_5"] = self.label_5

        if stage.stageNum != 1:
            self.DeleteButton = QtWidgets.QPushButton(self.groupBox, clicked = lambda : stage.removeStage())
            self.DeleteButton.setGeometry(QtCore.QRect(380, 10, 31, 31))
            font = QtGui.QFont()
            font.setPointSize(8)
            self.DeleteButton.setFont(font)
            self.DeleteButton.setObjectName("DeleteButton")

            stage.elements["DeleteButton"] = self.DeleteButton
            self.DeleteButton.setText(_translate("TimingsDialog", "X"))

        
        self.groupBox.setTitle(_translate("TimingsDialog", f"Stage {stage.stageNum}"))
        self.label.setText(_translate("TimingsDialog", "Week(s)"))
        self.label_2.setText(_translate("TimingsDialog", "Day(s)"))
        self.label_3.setText(_translate("TimingsDialog", "Hour(s)"))
        self.label_4.setText(_translate("TimingsDialog", "Minute(s)"))
        self.label_5.setText(_translate("TimingsDialog", "Second(s)"))

    def closeWindow(self):
        self.TimingsDialog.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TimingsDialog = QtWidgets.QDialog()
    ui = Ui_TimingsDialog()
    ui.setupUi(TimingsDialog)
    TimingsDialog.show()


    sys.exit(app.exec_())
